"""Add new columns and tables for Community features

Revision ID: 0470fc653b5b
Revises: b08819176d62
Create Date: 2026-07-26 12:47:17.873958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0470fc653b5b'
down_revision: Union[str, Sequence[str], None] = 'b08819176d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketitem', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketitem', 'image_url')
    # ### end Alembic commands ###
