"""Hazard Updates

Revision ID: 17ca3be657d6
Revises: 0470fc653b5b
Create Date: 2026-07-26 14:24:57.297198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17ca3be657d6'
down_revision: Union[str, Sequence[str], None] = '0470fc653b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hazardreport', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('category')

    with op.batch_alter_table('marketitem', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Available'"))

    with op.batch_alter_table('researchjob', schema=None) as batch_op:
        batch_op.alter_column('preferred_time',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researchjob', schema=None) as batch_op:
        batch_op.alter_column('preferred_time',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('marketitem', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Available'"))

    with op.batch_alter_table('hazardreport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=False))
        batch_op.alter_column('severity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
