"""Add password

Revision ID: 9923c8311c44
Revises: 9fb981618060
Create Date: 2026-07-21 00:31:04.535100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9923c8311c44'
down_revision: Union[str, Sequence[str], None] = '9fb981618060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite alter column skipped
    op.add_column('user', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.alter_column('researchjob', 'preferred_time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
